// <auto-generated />
namespace Event.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CreateAllTheTables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CreateAllTheTables));
        
        string IMigrationMetadata.Id
        {
            get { return "202012040043312_CreateAllTheTables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
